### ISSUE TITLE
AssertionError: Assigned values have not the same length than fitness weights

### ISSUE THREAD

**Issue by anishthite** [ezCGP/ezCGP#240]
Getting this on the main simgan branch, haven't made any changes other than some small plotting stuff, so not sure hwy its happening. I'll look more at it
```
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    main(problem_filename, problem_output_directory, args.previous_run, seed, args.loglevel)
  File "main.py", line 117, in main
    universe.run(problem)
  File "/home/athite3-gtri/ezCGP/codes/universe.py", line 217, in run
    self.evaluate_score_population(problem)
  File "/home/athite3-gtri/ezCGP/codes/universe.py", line 427, in evaluate_score_population
    problem.objective_functions(self.population)
  File "/home/athite3-gtri/ezCGP/problems/problem_definition.py", line 63, in inner
    func(self, population)
  File "/home/athite3-gtri/ezCGP/problems/problem_simgan.py", line 128, in objective_functions
    population.population[indx].fitness.values = (rating, fid)
  File "/home/athite3-gtri/ezCGP/codes/genetic_material.py", line 152, in setValues
    super().setValues(values)
  File "/home/athite3-gtri/.conda/envs/simgan-cgp/lib/python3.7/site-packages/deap/base.py", line 188, in setValues
    assert len(values) == len(self.weights), "Assigned values have not the same length than fitness weights"
AssertionError: Assigned values have not the same length than fitness weights
```

**Comment by roddtalebi** [comment]
https://github.com/ezCGP/ezCGP/commit/c0acba6c815b5119c32abacea1259b2090169f24

https://github.com/ezCGP/ezCGP/pull/237#issuecomment-1039768417

;)
